--D.Esquema
<?xml version="1.0"?>
<!DOCTYPE Course_Catalog[
	<!ELEMENT Course_Catalog(Department)>
		<!ELEMENT Department(Title,Chair,Course+)>
			<!ELEMENT Title (#PCDATA)>
			<!ELEMENT Chair(Professor+)>
                <!ELEMENT Professor (First_Name, Last_Name)>
                    <!ELEMENT First_Name (#PCDATA)>
                    <!ELEMENT Last_Name (#PCDATA)>
			<!ELEMENT Course (Title*, Description*, Instructors*,Prerequisites*)>
				<!ELEMENT Title (#PCDATA)>
				<!ELEMENT Description (#PCDATA)>
				<!ELEMENT Instructors(Lecturer+,Professor*)>
					<!ELEMENT Lecturer(First_Name, Last_Name)>
                        <!ELEMENT First_Name (#PCDATA)>
                        <!ELEMENT Middle_Initial (#PCDATA)>
                        <!ELEMENT Last_Name (#PCDATA)>
                    <!ELEMENT Professor (First_Name, Last_Name)>
                        <!ELEMENT First_Name (#PCDATA)>
                        <!ELEMENT Last_Name (#PCDATA)>
                <!ELEMENT Prerequisites(Prereq*)>
                    <!ELEMENT Prerequisites(#PCDATA)>
            <!ATTLIST Department
                Code CDATA #REQUIRED>
            <!ATTLIST Course
                Number CDATA #REQUIRED
                Enrollment CDATA #REQUIRED>
]>

PUNTO DOS. (XML – Oracle) Linked-us. Formación 
1) 
<?xml version="1.0"?>
<!DOCTYPE Validaciones[
    <!ELEMENT Validaciones(Proyectos+)>
        <!ELEMENT Proyectos (Nombre, Año, Rol, Evaluacion)>
            <!ELEMENT Nombre (#PCDATA)>
            <!ELEMENT Año (#PCDATA)>
            <!ELEMENT Rol (#PCDATA)>
            <!ELEMENT Evaluacion (#PCDATA)>    
]>

-- XML Nook
-- XML NoOK: Hay más de un nodo raíz (Validacion,Perfil)
<Validaciones>
    <Proyectos>
        <Nombre> Ayuda tu planeta </Nombre>
        <Año> 2011 </Año>
        <Rol> Director </Rol>
        <Evaluacion>  </Evaluacion>
    </Proyectos>
</Validaciones>
<Perfil>
</Perfil>

--XML NoOK: Los conocimientos no pude ser vacio por lo definido en el DTD
<Validaciones>
    <Proyectos>
        <Nombre> Ayuda tu planeta </Nombre>
        <Año> </Año>
        <Rol> Director </Rol>
        <Evaluacion>  </Evaluacion>
    </Proyectos>
</Validaciones>

--XML NoOK: Etiqueta (Curso) no definida en dtd 
<Validaciones>
    <Proyectos>
        <Curso> 304 </Curso>
        <Nombre> Ayuda tu planeta </Nombre>
        <Año> </Año>
        <Rol> Director </Rol>
        <Evaluacion>  </Evaluacion>
    </Proyectos>
</Validaciones>

-- XMLOK
--OK1
<Validaciones>
    <Proyectos>
        <Nombre> Todos por todos </Nombre>
        <Año> 2010 </Año>
        <Rol> Inversor </Rol>
        <Evaluacion>  </Evaluacion>
    </Proyectos>
</Validaciones>

--OK2
<Validaciones>
    <Proyectos>
        <Nombre> Oculus Rift </Nombre>
        <Año> 2018 </Año>
        <Rol> Contribuyente </Rol>
        <Evaluacion>  </Evaluacion>
    </Proyectos>
</Validaciones>

--OK3
<Validaciones>
    <Proyectos>
        <Nombre> Web bunkers </Nombre>
        <Año> 2000 </Año>
        <Rol> Director </Rol>
        <Evaluacion>  </Evaluacion>
    </Proyectos>
</Validaciones>

--OK4
<Validaciones>
    <Proyectos>
        <Nombre> Readly </Nombre>
        <Año> 2005 </Año>
        <Rol> Inversor </Rol>
        <Evaluacion>  </Evaluacion>
    </Proyectos>
</Validaciones>


